[package]
name = "carveout"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2021"

[dependencies]
winit = "0.27.2"
wgpu = { version = "0.13.1", features = [ "spirv" ] }

egui = "0.19.0"
egui-wgpu = "0.19.0"
egui-winit = "0.19.0"

lyon = "1.0.0"
palette = { version = "0.6.0", features = [ "serializing" ] }

nalgebra = { version = "0.31.1", features = [ "bytemuck", "serde-serialize" ] }
parry2d = "0.9.0"
typed-spaces = { git = "https://github.com/lu15w1r7h/typed-spaces.git" }

tracing = "0.1.26"
tracing-subscriber = "0.3.15"

serde = { version = "1.0.143", features = [ "derive" ] }
typetag = "0.2.3"
ron = "0.8"

encase = { version = "0.3.0", features = [ "nalgebra" ] }
bytemuck = { version = "1.7.2", features = [ "derive" ] }
chrono = { version = "0.4.19", features = [ "serde" ] }
directories = "4.0.1"

futures = "0.3.16"
once_cell = "1.13.0"
replace_with = "0.1.7"
dyn-clone = "1.0.9"
egui_file = "0.2.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3
