[package]
name = "carveout"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2021"

[dependencies]
winit = "0.26.1"
wgpu = { version = "0.13.1", features = [ "spirv" ] }

egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui" }
egui-winit = { git = "https://github.com/emilk/egui" }

#lyon = "1.0.0"
lyon = { git = "https://github.com/lu15w1r7h/lyon" }
palette = "0.6.0"

tracing = "0.1.26"
tracing-subscriber = "0.3.15"

bytemuck = { version = "1.7.2", features = [ "derive" ] }
dirs = "4.0.0"
chrono = "0.4.19"
euclid = { version = "0.22.7", features = [ "bytemuck" ] }

futures = "0.3.16"
once_cell = "1.13.0"
replace_with = "0.1.7"
nalgebra = "0.31.1"
