[package]
name = "carveout"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2021"

[dependencies]
winit = "0.26.1"
wgpu = { version = "0.13.1", features = [ "spirv" ] }

egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui" }
egui-winit = { git = "https://github.com/emilk/egui" }

#lyon = "1.0.0"
lyon = { git = "https://github.com/lu15w1r7h/lyon" }
palette = { version = "0.6.0", features = [ "serializing" ] }

nalgebra = { version = "0.31.1", features = [ "bytemuck", "serde-serialize" ] }
parry2d = "0.9.0"
simba = "0.7.2"
approx = "0.5.1"
num-traits = "0.2.15"

tracing = "0.1.26"
tracing-subscriber = "0.3.15"

serde = { version = "1.0.143", features = [ "derive" ] }
ron = "0.8"

encase = { version = "0.3.0", features = [ "nalgebra" ] }
bytemuck = { version = "1.7.2", features = [ "derive" ] }
chrono = "0.4.19"
dirs = "4.0.0"
uuid = { version = "1.1.2", features = [ "v4", "fast-rng", "macro-diagnostics", "serde" ] }

futures = "0.3.16"
once_cell = "1.13.0"
replace_with = "0.1.7"
rfd = "0.10.0"

